
language: python

python:
  - { PATH: "{{Python39}}",
      VERSION: 3.9,
      DIST: std,
      PYINT: python3.9,
      PYTHONPATH: src }
  
virtualenv:
  - path: {{ospathjoin(root_path, pickname("$NAME_JENKINS", project_name + "_$VERSION_$DIST_$NAME"), "_venv")}}
  
install:
  - $PYINT -m pip install --upgrade pip
  - $PYINT -m pip install --upgrade --no-cache-dir --no-deps --index http://localhost:8067/simple/ onnxruntime scikit-learn --extra-index-url=https://pypi.python.org/simple/
  - $PYINT -m pip install --upgrade --no-cache-dir --no-deps --index http://localhost:8067/simple/ pyquickhelper tkinterquickhelper pyensae pymmails pymyinstall pyrsslocal mlstatpy mlinsights jyquickhelper manydataapi skl2onnx onnx onnxconverter_common mlprodict cpyquickhelper pandas-streaming --extra-index-url=https://pypi.python.org/simple/
  - $PYINT -m pip install -r requirements.txt
  - $PYINT -m pip install aequitas --no-deps
  - $PYINT --version
  - $PYINT -m pip freeze
  - export AUDIODEV=null
  - export SDL_VIDEODRIVER=dummy
  - export SDL_AUDIODRIVER=disk
  - export DISPLAY=localhost:0.0

script:
  - { CMD: "$PYINT -u setup.py unittests -g \".*((http)|(SKIP)|(LONG)|(GUI)|(cvxopt)|(theano)|(code_style)|(cartopy)).*\"", NAME: "UT", TIMEOUT: 3600 }  # timeout is 3600 for the documentation
  - { CMD: "$PYINT -u setup.py unittests -e \".*code_style.*\"", NAME: "UT_STYLE", SCHEDULER: "H H(1-2) 24 * *" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*cartopy.*\"", NAME: "UT_MAP", SCHEDULER: "H H(1-2) 24 * *" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*(http).*\"", NAME: "UT_HTTP", SCHEDULER: "H H(1-2) 24 * *" }
  - { CMD: "$PYINT -u setup.py unittests -e .*LONG.* -g \".*((internet)|(cvxopt)|(notebook_eleves)|(cartopy)).*\"", NAME: "UT_LONG", TIMEOUT: 3600, SCHEDULER: "H H(1-2) 24 * *" }
  - { CMD: "$PYINT -u setup.py unittests -e .*SKIP.* -g \".*((theano)|(keras)|(deep)|(scraping)|(pythonnet)|(huge)|(web)|(ete3)|(cvxopt)|(students)|(cartopy)).*\"", NAME: "UT_SKIP", SCHEDULER: "H H(1-2) 24 * *" }
  - { CMD: "$PYINT -u setup.py unittests -e .*_1A_.* -g \".*((SKIP)|(theano)|(keras)|(scraping)|(ete3)|(cvxopt)|(cartopy)).*\"", NAME: "UT_1A", SCHEDULER: "H H(1-2) 24 * *" }
  - { CMD: "$PYINT -u setup.py unittests -e .*_2A_.* -g \".*((SKIP)|(theano)|(keras)|(scraping)|(ete3)|(cvxopt)|(cartopy)).*\"", NAME: "UT_2A", TIMEOUT: 3600, SCHEDULER: "H H(1-2) 24 * *" }
  - { CMD: "$PYINT -u setup.py unittests -e .*_3A_.* -g \".*((SKIP)|(theano)|(keras)|(scraping)|(ete3)|(cvxopt)|(cartopy)).*\"", NAME: "UT_3A", SCHEDULER: "H H(1-2) 24 * *" }
  - { CMD: "$PYINT -u setup.py unittests -e .*_EX_.* -g \".*((SKIP)|(theano)|(keras)|(scraping)|(ete3)|(cvxopt)|(cartopy)).*\"", NAME: "UT_EX", TIMEOUT: 3600, SCHEDULER: "H H(1-2) 24 * *" }
  - { CMD: "$PYINT -u setup.py unittests -e .*_GUI_.* -g \".*((SKIP)|(theano)|(keras)|(scraping)|(ete3)|(cvxopt)|(cartopy)).*\"", NAME: "UT_GUI", TIMEOUT: 2400, SCHEDULER: "H H(1-2) 24 * *" }
  - { CMD: "$PYINT -u setup.py unittests -e .*scraping.* -g \".*((SKIP)|(theano)|(keras)|(ete3)|(cvxopt)).*\"", NAME: "UT_SCRAPING", TIMEOUT: 3600, SCHEDULER: "H H(1-2) 24 * *" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*huge.*\"", NAME: "UT_HUGE", SCHEDULER: "H H(1-2) 24 * *" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*cvxopt.*\"", NAME: "UT_CVXOPT", SCHEDULER: "H H(1-2) 24 * *" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*notebook_eleves.*\"", NAME: "UT_NBELEVE", SCHEDULER: "H H(1-2) 24 * *" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*students.*\"", NAME: "UT_STUDENTS", SCHEDULER: "H H(1-2) 24 * *" }
  - { CMD: "$PYINT -u setup.py unittests -e \".*internet.*\"", NAME: "UT_INTERNET", SCHEDULER: "H H(1-2) 24 * *" }

after_script:
  - $PYINT -u setup.py bdist_wheel
  - if [ ${VERSION} == "3.9" and ${DIST} != "conda" and ${NAME} == "UT" ] then cp dist/*.whl {{root_path}}/../local_pypi/local_pypi_server fi

documentation:
  # The first run of the documentation may fail, the second goes one.
  - if [ ${NAME} == "UT" ] then $PYINT -u setup.py build_sphinx fi
  - if [ ${NAME} == "UT" ] then cp -R -f _doc/sphinxdoc/build/html dist/html fi
  - if [ ${NAME} == "UT" ] then cp -R -f _doc/sphinxdoc/build/html dist/html3 fi
