dist: focal
sudo: true
language: python
python:
  - "3.9"
addons:
-  apt:
-    packages:
      - ffmpeg
      - build-dep
      - graphviz
      - libgfortran3
      - libblas-dev
      - liblapack-dev
      - gfortran      
      - libgeos-dev

env:
  global:
    - LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
    - SEGFAULT_SIGNALS=all
    - PYTHONUNBUFFERED=True
    - SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=disk

install:
  - sudo apt-get install libgeos-dev libproj-dev proj-data graphviz libblas-dev liblapack-dev
  - wget https://apt.llvm.org/llvm.sh
  - chmod +x llvm.sh
  - sudo ./llvm.sh 10
  - ls /usr/bin/llvm*
  - export LLVM_CONFIG=/usr/bin/llvm-config
  # extra dependencies
  # - pip install -U git+https://github.com/sdpython/pyPdf --no-deps
  - pip install -r requirements.txt
  - pip uninstall -y shapely
  - pip install --no-binary shapely shapely
  - export PYTHONPATH=src

script:
  - python setup.py unittests
